### ISSUE TITLE
align left align right same line

### ISSUE THREAD

**Issue by bdlaureano** [PyramidTechnologies/Phoenix-ESC-POS#2]
Hello, how can I have left aligned the item name, and at the right in the same line the item price?
Thanks.

**Comment by ghost** [comment]
Using tabs positions is the best way to do this: http://reliance-escpos-commands.readthedocs.io/en/latest/cursor_position.html?highlight=1b%2044

**Comment by ghost** [comment]
Whoops, I thought we were talking about Reliance, not Phoenix! Sorry!

For Phoenix, you will need to tab or space this out to create your alignment. Luckily the font is monospace so that shouldn't be too difficult. https://pyramidacceptors.com/pdf/PHX_ESC_POS_Protocol.pdf
