### ISSUE TITLE
Phoenix Printer wrong results

### ISSUE THREAD

**Issue by jmbidev** [PyramidTechnologies/Phoenix-ESC-POS#3]
Hello!
I'm having trouble with the results I'm getting. 
I'm using a usb to db9 adapter to connect the serial printer with my PC and I don't know if that could be the cause or not. 
Commands like LF, font efects, font justify and others are not working. 
The only thing I'm able to do is write text and CR (that works as new line). 
After 4 lines printed (with CR at the end) the paper automatically comes out and doesn't wait for 30 secs.
Also Phoenix Tools doesn't connect to the printer. Should I use usb cable instead?
I can't even make the example work as it's supposed to.
If I use full cut command it cuts the paper and doesn't care if it's the right length (doesn't come out).
Any clue what's going on? 

Thanks

**Comment by corytodd** [comment]
Sounds like you might not have the right firmware. If you send an email to support@pyramidacceptors.com they can get you setup. You might also need to configure your line endings with the Phoenix Tools program.

**Comment by corytodd** [comment]
Sorry, I missed your other question about Phoenix Tools at the end there. Phoenix Tools requires that you connect to the USB port on the Phoenix.

**Comment by jmbidev** [comment]
Ok, I thought I could use Phoenix Tools by using rj45 - db9 connection. 
I will try using the usb port instead. 
Thank you!
