### ISSUE TITLE
PHX-USB communication over rs232

### ISSUE THREAD

**Issue by dp5306** [PyramidTechnologies/Phoenix-ESC-POS#4]
Hello, i have the PHX-USB thermal printer, can it communicate with the rs232 protocol (ESC/POS over serial), using the RJ-45 to DB9 adapter you are selling? Printing over USB is not an option for me.

**Comment by corytodd** [comment]
Hi there, no the PHX-USB model does not support ESC/POS over the RJ-45 port. If you contact our support@pyramidacceptors.com they can get you information on the right model.
